### PR TITLE
Multiple volumes fix and support for secure LDAP

### PR DESCRIPTION
**Pull request by timlegge**
Not sure if this is the best way.  I commented out the volume files to show where a user would add the proper configuration files.  I added the ldap.conf and a ROOT-CA.pem file that can be used to add their own CA certificate

### CODE REVIEW

**Comment by timlegge** [comment]
Fixes #72

**Review by Schrolli91 — COMMENTED** [review]
I don't know about ldap - maybe someone other has to check that
but from compose file side that should be ok

**Comment by timlegge** [comment]
> I don't know about ldap - maybe someone other has to check that
> but from compose file side that should be ok

The unfortunate thing about ldaps is it is different every where depending on the location that distro keeps its config files and certs.

The ldap container could get updated to support ldaps so a working version exists.  However this config worked with the fpm-alpine container against a windows ldaps server as you say since its commented out is essentially makes it easier if someone want to do ldaps in the future.  As for me saml is now in the main repo and I am done with ldap

**Comment by timlegge** [comment]
@tobybatch ypu might have missed this one too

**Comment by Schrolli91** [comment]
@tobybatch Ping?

**Pull request merged**
