### PR TITLE
trying to fix auto build

### PR DESCRIPTION
**Pull request by kevinpapst**
@tobybatch there is a new release available, but instead of manually building it - I would really like to fix this script

Too many people rely on this docker image and we should make sure that it is available after my release.

As it is not working by now, I am committing directly until it works^^ might be a bit off email spam coming in ...

### CODE REVIEW

**Comment by kevinpapst** [comment]
alright, I cannot commit and cannot merge ... that is a bit annoying. my spirit was killed instantly 😁

**Review by tobybatch — APPROVED** [review]

**Comment by kevinpapst** [comment]
Thanks. Too bad, re-running the job from 5 days ago does not use the updated script.
Any idea how we can test this without me having to create invalid tags?

**Comment by tobybatch** [comment]
Yes, I can run actions locally. Send me the payload you dispatch and I will try and fix it. I'll build manually for now.

**Comment by kevinpapst** [comment]
Can you re-use the payload from the failed action? It is in JSON format:
```
{
    "event": {
        "action": "released",
        "release": {
            "assets": [],
            "assets_url": "https://api.github.com/repos/kevinpapst/kimai2/releases/60618206/assets",
            "author": {
                "avatar_url": "https://avatars.githubusercontent.com/u/533162?v=4",
                "events_url": "https://api.github.com/users/kevinpapst/events{/privacy}",
                "followers_url": "https://api.github.com/users/kevinpapst/followers",
                "following_url": "https://api.github.com/users/kevinpapst/following{/other_user}",
                "gists_url": "https://api.github.com/users/kevinpapst/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/kevinpapst",
                "id": 533162,
                "login": "kevinpapst",
                "node_id": "MDQ6VXNlcjUzMzE2Mg==",
                "organizations_url": "https://api.github.com/users/kevinpapst/orgs",
                "received_events_url": "https://api.github.com/users/kevinpapst/received_events",
                "repos_url": "https://api.github.com/users/kevinpapst/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/kevinpapst/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kevinpapst/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/kevinpapst"
            },
            "body": "\r\n[Full Changelog](https://github.com/kevinpapst/kimai2/compare/1.18...1.18.1)\r\n\r\n**PHP Version compatibility:**\r\n- PHP 7.3 might work, but untested\r\n - PHP 7.4 and PHP 8 supported\r\n - PHP 8.1 does not support LDAP yet, other problems might exist\r\n\r\n**Implemented enhancements:**\r\n- Activated language `Persian`\r\n- Added and activated language `Norwegian Bokmål` - thanks @comradekingu \r\n- Added comment to customer/project/activity entity and collections API\r\n\r\n**Fixed bugs:**\r\n- Fix: translation file extensions / activate missing translations in `de_CH`, `pt_BR`, `zh_CN`\r\n- Fix: title pattern when description is included in customer/project/activity dropdown\r\n",
            "created_at": "2022-02-28T15:32:41Z",
            "draft": false,
            "html_url": "https://github.com/kevinpapst/kimai2/releases/tag/1.18.1",
            "id": 60618206,
            "mentions_count": 1,
            "name": "1.18.1",
            "node_id": "RE_kwDOBELIZs4DnPXe",
            "prerelease": false,
            "published_at": "2022-02-28T15:40:07Z",
            "tag_name": "1.18.1",
            "tarball_url": "https://api.github.com/repos/kevinpapst/kimai2/tarball/1.18.1",
            "target_commitish": "master",
            "upload_url": "https://uploads.github.com/repos/kevinpapst/kimai2/releases/60618206/assets{?name,label}",
            "url": "https://api.github.com/repos/kevinpapst/kimai2/releases/60618206",
            "zipball_url": "https://api.github.com/repos/kevinpapst/kimai2/zipball/1.18.1"
        },
        "repository": {
            "allow_forking": true,
            "archive_url": "https://api.github.com/repos/kevinpapst/kimai2/{archive_format}{/ref}",
            "archived": false,
            "assignees_url": "https://api.github.com/repos/kevinpapst/kimai2/assignees{/user}",
            "blobs_url": "https://api.github.com/repos/kevinpapst/kimai2/git/blobs{/sha}",
            "branches_url": "https://api.github.com/repos/kevinpapst/kimai2/branches{/branch}",
            "clone_url": "https://github.com/kevinpapst/kimai2.git",
            "collaborators_url": "https://api.github.com/repos/kevinpapst/kimai2/collaborators{/collaborator}",
            "comments_url": "https://api.github.com/repos/kevinpapst/kimai2/comments{/number}",
            "commits_url": "https://api.github.com/repos/kevinpapst/kimai2/commits{/sha}",
            "compare_url": "https://api.github.com/repos/kevinpapst/kimai2/compare/{base}...{head}",
            "contents_url": "https://api.github.com/repos/kevinpapst/kimai2/contents/{+path}",
            "contributors_url": "https://api.github.com/repos/kevinpapst/kimai2/contributors",
            "created_at": "2016-10-20T17:06:34Z",
            "default_branch": "master",
            "deployments_url": "https://api.github.com/repos/kevinpapst/kimai2/deployments",
            "description": "Kimai v2 is a web-based multiuser time-tracking application. Free for everyone: freelancers, agencies, companies, organizations - all can track their times, generate invoices and more. SaaS version available at https://www.kimai.cloud",
            "disabled": false,
            "downloads_url": "https://api.github.com/repos/kevinpapst/kimai2/downloads",
            "events_url": "https://api.github.com/repos/kevinpapst/kimai2/events",
            "fork": false,
            "forks": 360,
            "forks_count": 360,
            "forks_url": "https://api.github.com/repos/kevinpapst/kimai2/forks",
            "full_name": "kevinpapst/kimai2",
            "git_commits_url": "https://api.github.com/repos/kevinpapst/kimai2/git/commits{/sha}",
            "git_refs_url": "https://api.github.com/repos/kevinpapst/kimai2/git/refs{/sha}",
            "git_tags_url": "https://api.github.com/repos/kevinpapst/kimai2/git/tags{/sha}",
            "git_url": "git://github.com/kevinpapst/kimai2.git",
            "has_downloads": true,
            "has_issues": true,
            "has_pages": false,
            "has_projects": false,
            "has_wiki": false,
            "homepage": "https://www.kimai.org",
            "hooks_url": "https://api.github.com/repos/kevinpapst/kimai2/hooks",
            "html_url": "https://github.com/kevinpapst/kimai2",
            "id": 71485542,
            "is_template": false,
            "issue_comment_url": "https://api.github.com/repos/kevinpapst/kimai2/issues/comments{/number}",
            "issue_events_url": "https://api.github.com/repos/kevinpapst/kimai2/issues/events{/number}",
            "issues_url": "https://api.github.com/repos/kevinpapst/kimai2/issues{/number}",
            "keys_url": "https://api.github.com/repos/kevinpapst/kimai2/keys{/key_id}",
            "labels_url": "https://api.github.com/repos/kevinpapst/kimai2/labels{/name}",
            "language": "PHP",
            "languages_url": "https://api.github.com/repos/kevinpapst/kimai2/languages",
            "license": {
                "key": "mit",
                "name": "MIT License",
                "node_id": "MDc6TGljZW5zZTEz",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit"
            },
            "merges_url": "https://api.github.com/repos/kevinpapst/kimai2/merges",
            "milestones_url": "https://api.github.com/repos/kevinpapst/kimai2/milestones{/number}",
            "mirror_url": null,
            "name": "kimai2",
            "node_id": "MDEwOlJlcG9zaXRvcnk3MTQ4NTU0Mg==",
            "notifications_url": "https://api.github.com/repos/kevinpapst/kimai2/notifications{?since,all,participating}",
            "open_issues": 185,
            "open_issues_count": 185,
            "owner": {
                "avatar_url": "https://avatars.githubusercontent.com/u/533162?v=4",
                "events_url": "https://api.github.com/users/kevinpapst/events{/privacy}",
                "followers_url": "https://api.github.com/users/kevinpapst/followers",
                "following_url": "https://api.github.com/users/kevinpapst/following{/other_user}",
                "gists_url": "https://api.github.com/users/kevinpapst/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/kevinpapst",
                "id": 533162,
                "login": "kevinpapst",
                "node_id": "MDQ6VXNlcjUzMzE2Mg==",
                "organizations_url": "https://api.github.com/users/kevinpapst/orgs",
                "received_events_url": "https://api.github.com/users/kevinpapst/received_events",
                "repos_url": "https://api.github.com/users/kevinpapst/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/kevinpapst/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kevinpapst/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/kevinpapst"
            },
            "private": false,
            "pulls_url": "https://api.github.com/repos/kevinpapst/kimai2/pulls{/number}",
            "pushed_at": "2022-02-28T15:40:07Z",
            "releases_url": "https://api.github.com/repos/kevinpapst/kimai2/releases{/id}",
            "size": 37538,
            "ssh_url": "git@github.com:kevinpapst/kimai2.git",
            "stargazers_count": 1594,
            "stargazers_url": "https://api.github.com/repos/kevinpapst/kimai2/stargazers",
            "statuses_url": "https://api.github.com/repos/kevinpapst/kimai2/statuses/{sha}",
            "subscribers_url": "https://api.github.com/repos/kevinpapst/kimai2/subscribers",
            "subscription_url": "https://api.github.com/repos/kevinpapst/kimai2/subscription",
            "svn_url": "https://github.com/kevinpapst/kimai2",
            "tags_url": "https://api.github.com/repos/kevinpapst/kimai2/tags",
            "teams_url": "https://api.github.com/repos/kevinpapst/kimai2/teams",
            "topics": [
                "adminlte",
                "doctrine",
                "freelancers",
                "invoice",
                "invoicing",
                "kimai",
                "multilanguage",
                "php",
                "php7",
                "self-hosted",
                "symfony",
                "symfony-application",
                "symfony4",
                "time-tracker",
                "time-tracking",
                "timetracker",
                "timetracking",
                "twig",
                "user-management"
            ],
            "trees_url": "https://api.github.com/repos/kevinpapst/kimai2/git/trees{/sha}",
            "updated_at": "2022-02-27T20:31:28Z",
            "url": "https://api.github.com/repos/kevinpapst/kimai2",
            "visibility": "public",
            "watchers": 1594,
            "watchers_count": 1594
        },
        "sender": {
            "avatar_url": "https://avatars.githubusercontent.com/u/533162?v=4",
            "events_url": "https://api.github.com/users/kevinpapst/events{/privacy}",
            "followers_url": "https://api.github.com/users/kevinpapst/followers",
            "following_url": "https://api.github.com/users/kevinpapst/following{/other_user}",
            "gists_url": "https://api.github.com/users/kevinpapst/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/kevinpapst",
            "id": 533162,
            "login": "kevinpapst",
            "node_id": "MDQ6VXNlcjUzMzE2Mg==",
            "organizations_url": "https://api.github.com/users/kevinpapst/orgs",
            "received_events_url": "https://api.github.com/users/kevinpapst/received_events",
            "repos_url": "https://api.github.com/users/kevinpapst/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/kevinpapst/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/kevinpapst/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/kevinpapst"
        }
    }
}

```

**Comment by tobybatch** [comment]
1.18.1 is on dockerhub now. I'll look at this issue this weekend

**Comment by kevinpapst** [comment]
Thanks Toby!

**Pull request merged**
