### PR TITLE
Add Dependabot

### PR DESCRIPTION
**Pull request by jokay**
Adds the [Dependabot](https://github.com/marketplace/dependabot-preview).

### CODE REVIEW

**Review by Schrolli91 — APPROVED** [review]
Never used Dependabot till now - but sounds like a good idea here

**Comment by jokay** [comment]
You can see it in action [here](https://github.com/x-jokay/docker-php-fpm-ext/pull/1) 😉

**Comment by kevinpapst** [comment]
Dependabot can get rather annoying if you have many dependencies 😁 but its really helping as well. 
I like the idea to add it here.

**Comment by Schrolli91** [comment]
especially for bumping the docker bases automatically its a nice thing, i think

**Pull request merged**
