### PR TITLE
Fix "KIMAI" arg, vulnerabilities and more

### PR DESCRIPTION
**Pull request by hexxone**
Hi there, I'm following up to #476 .

I took some time to fix the main issue, by passing through the "KIMAI" arg in the correct places in Dockerfile.
While I was at it, I did the same for "TIMEZONE" (previously "TZ").

Then I noticed there are some vulnerabilities included due to an outdated PHP Version being used (8.1.12 & 8.1.13).
image

So I took the liberty to fix it by introducing two new arguments "PHP_VER" and "COMPOSER_VER" and now using PHP 8.1 (implicitly 8.1.16) and composer "latest".

Afterwards I was able to confirm that the "KIMAI" env var now gets set correctly and the PHP vulnerabilities are gone.
image

Everything seems to work accordingly for now.

Also refactored the Markdown files according to lint rules and added a "Manual build" Section in Contributing, incorporating the new Args.

Let me know what you think :)
Cheers

### CODE REVIEW

**Review by kevinpapst — CHANGES_REQUESTED** [review]
Thanks for taking the time to contribute 👍 

Can you split this PR into multiple smaller ones?

1. Updating the image itself 
2. Changing md files
3. Adding traefik (if @tobybatch wants to support that in the long run?)

Finally and most important: please **remove package-lock.json**.
Changing lock files is the task of the maintainer: changed lock files can include arbirary code which is way more dangerous than an outdated PHP version in a container.

**Comment by hexxone** [comment]
Alright, no problem and sorry 

Just give me some minutes :)

**Comment by kevinpapst** [comment]
Really no reason to be sorry, your input is very much appreciated 👍 

I am just trying to make the review and merge process as smooth as possible. Thanks for re-doing the PR!

**Comment by hexxone** [comment]
Ok, I hope its alright now :)

Let me know if theres something else.

**Pull request closed without merging**
