### PR TITLE
Fix wrong exposed port

### PR DESCRIPTION
**Pull request by Jerome1337**

### CODE REVIEW

**Comment by tobybatch** [comment]
@Jerome1337 Sorry to ask but why is it wrong to use the port 8001?

**Comment by Jerome1337** [comment]
@tobybatch Your README and your production Dockerfile are using `8080` port.

When you run the dev env with this current Dockerfile the PHP server expose `8001` and Docker try to export `8080`, so kimai is inaccessible.

It's not a problem with the `8001` port particularly

**Comment by tobybatch** [comment]
Thanks @Jerome1337 .  I've amended the port to be 8001 throughout. It's a long story but the dev docker file actually lives in the Kimai2 repo hosted by Kevin Papst.  It's easier for me to change my ports to match his.

If you are happy with this I'll close the PR as the changes are in master.

**Comment by kevinpapst** [comment]
I don't mind any change in the official repo, as long as it is documented for the users.

**Comment by Jerome1337** [comment]
@tobybatch Sound good :+1:

**Pull request closed without merging**
