### PR TITLE
added workflow file to build docker image upon kimai release

### PR DESCRIPTION
**Pull request by kevinpapst**
See #302 and https://github.com/kevinpapst/kimai2/pull/2882

I think this needs to be merged and then I can try to trigger events on my repo to see if this workflow starts.

Once this works we can change the contents of this workflow file to do "real work".

ping @tobybatch @Apfelwurm

### CODE REVIEW

**Comment by kevinpapst** [comment]
@tobybatch Could you please approve, I cannot merge without and I'd like to do further testing on the automation topic. As you can see, the actions doesn't really do anything...

**Review by tobybatch — APPROVED** [review]

**Comment by kevinpapst** [comment]
@tobybatch seems it worked: https://github.com/tobybatch/kimai2/actions/runs/1393752738

Now what would be the next step?
Shall I change the event on my repo to only trigger upon new releases?
Do you want to build development images on every "merge to master" in my repo?

**Comment by tobybatch** [comment]
@kevinpapst @Apfelwurm https://github.com/tobybatch/kimai2/blob/main/.github/workflows/docker-image.yml
Easy 80% is already done here. I need to add the tests, I will get around to it. It's just a time thing. At the moment I have https://github.com/tobybatch/kimai2/blob/main/.github/workflows/docker-image.yml

**Comment by tobybatch** [comment]
@kevinpapst I think for now on releases please, I'll wire that into my new workflow when it is done.

@apfelwurm Thanks for the push. I've been meaning to do this for ages.

**Comment by kevinpapst** [comment]
Okay, adjusted and merged on upstream. 
Now whenever you find the time @tobybatch you can adjust the file here and forget about manual builds upon new Kimai releases 🎉 

Thanks @Apfelwurm 👍

**Comment by Apfelwurm** [comment]
Thanks for your awsome work and response times! :)

**Pull request merged**
