### PR TITLE
fix: upgrade actions libs

### LINKED ISSUE #435: [TECH DEBT] Build deprecation warnings
**Is your feature request related to a problem? Please describe.**

The builds show a warning nowadays about deprecated GitHub action features, e.g.
https://github.com/tobybatch/kimai2/actions/runs/3566944034

Bildschirmfoto 2022-11-28 um 18 19 17

I fixed that in my builds mainly by bumping the versions in the workflow file.

E.g. from `uses: actions/checkout@v2` to `uses: actions/checkout@v3` in line
https://github.com/tobybatch/kimai2/blob/main/.github/workflows/kimai-release.yml#L18

### PR DESCRIPTION
**Pull request by tobybatch**
fixes #435

### CODE REVIEW

**Comment by kevinpapst** [comment]
You are on fire tonight 😁 👍

**Comment by kevinpapst** [comment]
keep that open

**Comment by kevinpapst** [comment]
we'll check later if that is still needed

**Comment by tobybatch** [comment]
Close this as I intend to re-write the CI process completely

**Comment by tobybatch** [comment]
I'll close this as I'm going totally rewrite the CI process

**Pull request closed without merging**
