### PR TITLE
No issue/read payload vars

### PR DESCRIPTION
**Pull request by tobybatch**

### CODE REVIEW

**Comment by tobybatch** [comment]
@kevinpapst I think I'm ready to test a release. At the moment I expect to the new kimai version to be in the payload as KIMAI_VERSION. Is that OK?

**Comment by kevinpapst** [comment]
@tobybatch The trigger does not set any payload. Can you fetch it with 
```
export VERSION=`curl --silent "https://api.github.com/repos/kevinpapst/kimai2/releases/latest"|grep '"tag_name":'|sed -E 's/.*"([^"]+)".*/\1/'`
```

That's what I use in my scripts.

Some more versions available here: https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c

**Comment by tobybatch** [comment]
Not easily. ;)

I'll see what I can do.

**Comment by kevinpapst** [comment]
Can you try something like that:
```
      - id: kimai-release
        uses: thebritican/fetch-latest-release@v2
        with:
          github_token: ${{ github.token }}
          repo_path: "kevinpapst/kimai2"
      - name: Set vars
         run: echo "kv=${{ steps.kimai-release.outputs. tag_name }}" >> $GITHUB_ENV
```

**Pull request merged**
