### PR TITLE
Docs add paypal

### PR DESCRIPTION
**Pull request by tobybatch**

### CODE REVIEW

**Comment by kevinpapst** [comment]
you removed the second kimai version? was that by accident? [I understood that it is required](https://github.com/tobybatch/kimai2/pull/187#issuecomment-721035764)

**Comment by Schrolli91** [comment]
Yes i think thats a accident because in my opinion its not redundant in this way

**Comment by tobybatch** [comment]
I though it would get inherited from the earlier ENV

**Comment by Schrolli91** [comment]
Have you checked this? I'm not sure at all... There was any reason why i added this twice...

**Comment by tobybatch** [comment]
I'm building now

**Comment by tobybatch** [comment]
You're right, it isn't set but also isn't needed. The container runs fine without it. The startup script does echo it into a file but that too is never used. Ok to remove.

**Comment by Schrolli91** [comment]
FYI:
my inital plan was, to use this version number (in the file) to check if an update of the files in public mount is needed

**Comment by tobybatch** [comment]
OK. @kevinpapst can we 'ask' kimai for it's version?  Is it stored somewhere?

**Comment by kevinpapst** [comment]
Lets continue here: https://github.com/tobybatch/kimai2/pull/187

**Pull request merged**
