### PR TITLE
Update containers

### PR DESCRIPTION
**Pull request by jokay**
Updates the used containers.

### CODE REVIEW

**Comment by jokay** [comment]
When using `alpine:3.11` it throws the following error:

```sh
ERROR: unsatisfiable constraints:mpfr3 (missing):required by: world[mpfr3] alpine
```

The package [mpfr3](https://pkgs.alpinelinux.org/packages?name=mpfr3&branch=v3.11&repo=main) is not available in alpine `> 3.10` branches anymore.

But `mpfr4` can be used instead :wink:

**Comment by jokay** [comment]
When using `composer:1.10` it throws the following error:

```sh
[RuntimeException]                        
  Failed to execute git show-ref --head -d  
                                            
  sh: git: not found
```

**Comment by x-jokay** [comment]
Currently it won't start ...

```sh
1.8
Using non mysql DB
first run - install kimai

In Kernel.php line 716:
                                                                    
  Unable to create the cache directory (/opt/kimai/var/cache/prod)  
                                                                    


In Kernel.php line 716:
                                                                    
  Unable to create the cache directory (/opt/kimai/var/cache/prod)  
                                                                    

Kimai2 ready
```

**Review by Schrolli91 — APPROVED** [review]
LGTM

**Review by tobybatch — APPROVED** [review]

**Pull request merged**
