### PR TITLE
Removed redundant kimai version

### LINKED ISSUE #185: [BUG] Kimai version mismatch
@tobybatch I just saw that there are different versions of Kimai mentioned in the Dockerfile.
Is that correct? Is the second variable even needed?

Compare Kimai 1.11.1

https://github.com/tobybatch/kimai2/blob/main/Dockerfile#L16-L18

with Kimai 1.8

https://github.com/tobybatch/kimai2/blob/main/Dockerfile#L178-L180

### PR DESCRIPTION
**Pull request by tobybatch**
closes #185

### CODE REVIEW

**Comment by Schrolli91** [comment]
I'm not sure that we can remove that.
There was some reason why i added it twice....

**Comment by kevinpapst** [comment]
Is it that easy? I thought the variable is used somewhere. Or is it populated from the first occurrence and taken over into that stage?

**Comment by Schrolli91** [comment]
The version is mentioned twice in the docker file....

- The first one is used to clone the sources from git
- The second is used as docker ENV var for the container (used in startup.sh)

**Comment by kevinpapst** [comment]
Too many discussion at once... now that the other PRs are merged, lets stay here for discussions 😁 re-posting [my comment](https://github.com/tobybatch/kimai2/issues/158#issuecomment-721054476):

@Schrolli91 Can we change that to something like:

```
if [ ! -f /opt/kimai/installed  ]; then bin/console kimai:version --short > /opt/kimai/installed ; else cat /opt/kimai/installed ; fi
```
Then the second variable can be avoided

**Comment by Schrolli91** [comment]
Yes thats a perfect solution at this point in my opinion

**Comment by tobybatch** [comment]
Excellent, I'll do that now.

**Pull request closed without merging**
