### PR TITLE
Fix public

### PR DESCRIPTION
**Pull request by tobybatch**

### CODE REVIEW

**Comment by kevinpapst** [comment]
That was a quick merge 😁 I would have added .idea to .gitignore to keep your own IDE files out of the repo

**Comment by tobybatch** [comment]
These days I'm on my own anyway :(

And keeping those with the repo is just me being lazy, so when I swap between my laptop and desktop I keep the runtime settings.

**Comment by tobybatch** [comment]
We should work out a web hook so we can auto build whenever you release. I'll flesh it out and create an issue in this repo.

**Comment by kevinpapst** [comment]
Yes, we should work on that webhook. I hope this is possible today with GitHub actions.

Probably you might want to add .idea to .gitattributes to prevent them from being exported on releases.

See this file for example https://github.com/kevinpapst/AdminLTEBundle/blob/master/.gitattributes

**Pull request merged**
