### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by tobybatch**

### CODE REVIEW

**Comment by kevinpapst** [comment]
I am not entirely sure if I understand the changes correct, so let me ask:
Whenever a Travis build runs in this repo, a new docker image for Kimai master is pushed to docker hub?

**Comment by tobybatch** [comment]
Basically yes. In the future I'd like to build tags as well be it's a little tricky as your repo is not the one linked to this Travis account.

**Comment by Schrolli91** [comment]
Simple Question - Why Travis and not Github Actions?

**Comment by kevinpapst** [comment]
> Basically yes 

Hm ... my thoughts on this, please correct me if I am wrong (I hope I am).

So every push in any PR in this repo will rebuild the master image. 
This push could be potentially broken => broken image on docker hub?
That new broken image is live until someone else pushes a commit to a working PR (or you do it locally)?

Thinking further:
Is it possible that someone pushes code that is potentially dangerous? Just from a theoretical point of view: could I open a PR that includes a build step which triggers a mysql command to drop the Kimai database? Or execute a `rm -rf` on a mounted folder?

Can we limit this travis build to only run on master builds / tags?
Should we use a trigger from Kimai instead? Like this one: 
https://github.community/t5/GitHub-Actions/Triggering-actions-by-other-repository-webhooks/td-p/32158

**Comment by tobybatch** [comment]
@Schrolli91 Coz I'm old and I've used travis for years and not GH actions.  I'll have a go at re-tooling it for GHA.

@kevinpapst You're right.  This only ever built your master and would not have pushed a broken build.  But I'll see about limiting it to tags and master when I switch it to GHA.

**Pull request closed without merging**
