### PR TITLE
Fix memory limit

### PR DESCRIPTION
**Pull request by tobybatch**
Adds a customer php.ini with ```memory_limit = -1``` for running console commands

### CODE REVIEW

**Comment by kevinpapst** [comment]
I use -1 in my own environment, but I am rather sure about what I do ^^ and I guess it is not best practice.

Maybe it is simpler to document a full command run (with temporary raised `memory_limit` only for the reset command):
```
php -D memory_limit=-1 bin/console kimai:reset-dev -n
```
Or raise the limit to 512MB instead of unlimited?

And one more question, becuase I am curious and have never seen/used it like that ... can you explain why that line works?
```
    sed "s/env php/env -S php -c /opt/kimai/php-cli.ini/g" /usr/local/etc/php/php.ini-development > /opt/kimai/php-cli.ini
```
Is PHP looking for an ini file in every directory where it runs a script in from, much like Apache does with .htaccess files for document roots?
What if someone executes bin/console but from another directory with an absolute path (like in the issue where the command is run from the docker host), will `/opt/kimai/php-cli.ini` be taken into account?

**Comment by tobybatch** [comment]
It's an error. I've conflalted two lines, hang on fix coming.  My fault for editing things before coffee (my youngest was up at 5)

**Comment by tobybatch** [comment]
The line should have been 

    sed -i "s/env php/env -S php -c /opt/kimai/php-cli.ini/g" /opt/kimai/bin/console

Which makes just the console command use -1 as the memory limit.

**Comment by kevinpapst** [comment]
Ah, a night like that... I was woken up today by a poke in my eye, happy parent mornings 😁 

I would have replace `<?php` with `<?php ini_set('memory_limit', '-1')` but, thats mostly because I didn't know that you can pass arguments in the interpreter line, great to learn something new!

**Review by kevinpapst — APPROVED** [review]
Not tested, review is based on what I see: LGTM 👍

**Review by Schrolli91 — APPROVED** [review]
I'm also not able to test this atm - but code looks ok to me.

**Pull request merged**
